# application-k8s.properties
management.endpoints.web.exposure.include=health,info
management.endpoint.health.probes.enabled=true# application-k8s.properties
management.endpoints.web.exposure.include=health,info
management.endpoint.health.probes.enabled=true